title: Center for Nanodevices, Integrated Circuits and Systems (CNICS)
description: Center for Excellence for nan
theme: just-the-docs

url: https://silicon-vlsi.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable/disable math supprt
math: latex 

